esphome:
  name: photobox-trigger

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "photobox"
  password: "photobox4matnel"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Photobox-Trigger"
    password: "enWbNOQBPMXL"

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    name: "PhotoTriggerButton"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

status_led:
  pin:
    number: GPIO8

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 24
    rmt_channel: 0
    chipset: ws2812
    name: "StatusLight"
    effects:
      - addressable_random_twinkle:
          name: IdleMode
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_rainbow:
          name: CountdownMode
          speed: 40
          width: 40

