@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A person standing in front of the photobox")


System_Boundary(photobox, "Photobox") {
    Container(app, "Application", "C++, Qt", "The main application that shows the live-view, initiates the photo capture, renders collages, schedules the prints, etc.")
    Container(cameraled, "CameraLed", "esphome", "Controls a connected LED ring located around the camera lens.")
    Container(buzzer, "Buzzer", "esphome", "Controls a connected switch and a LED ring that is integrated into the buzzer with the switch.")
}
System_Ext(printer, "Printer")
System_Ext(camera, "Camera", "A DSLR camera")


Rel(user, buzzer, "presses")
Rel(buzzer, app, "notifies", "HTTP,SSE")
Rel(app, cameraled, "set effects", "HTTP")

Rel_R(app, printer, "Sends print job", "cups")
Rel_L(app, camera, "Live feed, captures", "PTP")



@enduml
