esphome:
  name: photobox-trigger

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: "Fotobox"
  password: ""
  fast_connect: true  
  ap:
    ssid: "Photobox trigger fallback"
    password: ""

captive_portal:


web_server:
  port: 80
  local: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO23
      inverted: true
      mode:
        input: true
        pullup: true
    name: "PhotoTriggerButton"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO2
    num_leds: 12
    rmt_channel: 0
    chipset: ws2812
    name: "StatusLight"
    effects:
      - addressable_random_twinkle:
          name: IdleMode
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_rainbow:
          name: CountdownMode
          speed: 40
          width: 40
