esphome:
  name: photobox-camera

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "photobox"
  password: "photobox-matnel"
  fast_connect: true
  ap:
    ssid: "photobox-fallback"
    password: "photobox-matnel"
  on_connect:
    - light.addressable_set: 
        id: cameraLensLed
        green: 100%

  on_disconnect:
    - light.addressable_set: 
        id: cameraLensLed
        red: 100%

captive_portal:

web_server:
  port: 80

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 24
    rmt_channel: 0
    chipset: ws2812
    name: "CameraLensLight"
    id: cameraLensLed
    effects:
      - addressable_random_twinkle:
          name: IdleMode
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_rainbow:
          name: CountdownMode
          speed: 40
          width: 40
