name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      id-token: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build RPM
        uses: docker/build-push-action@v6
        with:
          tags: photobox-cross:latest
          outputs: type=local,dest=/opt/outdir
          target: artifact
          platforms: linux/arm64/v8

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: photobox-arm
          path: /opt/outdir/photobox.rpm
